spring:
  application:
    name: provider-eureka

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    appname: provider-eureka
info:
  name: ${spring.application.name}
